# Generated by Django 5.2 on 2025-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='crop_types',
        ),
        migrations.DeleteModel(
            name='CropType',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='crop_types',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
