# Generated by Django 5.2 on 2025-05-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_communitypost_crop_type_communitypost_disease_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='rust_detection',
        ),
    ]
